Removed empty JSX file.
Because when are using the `gatsby-plugin-i18n` package
and there is an empty JSX file in the `pages` directory,
the following exceptions will be raised:

WebpackError: a.type.toLowerCase is not a function in react-dom-server.node.production.min.js:36 a.renderDOM
See: https://github.com/gatsbyjs/gatsby/issues/4208